-- to run from DB2/Bin folder:
-- db2 -tvf "C:\work\repositories\MenuApi\MenuApi\scripts\db\db2\createMenuDB.sql"

connect to mydb1;

-- Create MENU Schema
DROP TABLE MENU.MENU;
DROP TABLE MENU.MENU_ITEM;
DROP SCHEMA MENU;
CREATE SCHEMA MENU AUTHORIZATION TEST;

-- Create Menu TABLE



CREATE TABLE MENU.MENU (
	ID SMALLINT GENERATED ALWAYS AS IDENTITY,
	NAME VARCHAR(30)
);

-- Create Menu_Item TABLE
CREATE TABLE MENU.MENU_ITEM (
	ID SMALLINT GENERATED ALWAYS AS IDENTITY,
	MENU_ID SMALLINT,
	NAME VARCHAR(30),
	DESCRIPTION VARCHAR(100)
);

GRANT SELECT ON MENU.MENU TO TEST;
GRANT SELECT ON MENU.MENU_ITEM TO TEST;